[package]
name = "nifty_net_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nifty_net.path = "../nifty_net"
bevy = "0.13"
serde = "1.0"
bincode = "1.3"
